# Generated by Django 5.0 on 2023-12-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ContactMe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
